esphome:
  name: p-nut
  friendly_name: P-NUT

esp32:
  board: esp32-p4-evboard
  variant: esp32p4
  flash_size: 16MB
  framework:
    type: esp-idf

ethernet:
  type: IP101
  mdc_pin: GPIO31
  mdio_pin: GPIO52
  clk:
    mode: CLK_EXT_IN
    pin: GPIO50
  power_pin: GPIO51
  phy_addr: 1

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

external_components:
  - source: github://lostsynapse/esphome-components
    components: [ups_hid, nut_server]

ups_hid:
  id: my_ups
  protocol: auto
  update_interval: 30s

nut_server:
  ups_hid_id: my_ups
  port: 3493